// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: msgid.proto

#pragma warning disable CS1591, CS0612, CS3021

[global::ProtoBuf.ProtoContract()]
public enum CMD
{
    LOGIN = 1,
    MAIN = 2,
    PVP = 3,
    INNER = 200,
}

[global::ProtoBuf.ProtoContract()]
public enum ACT
{
    INNER_SERVER_INFO = 1,
    LOGIN_BYSESSION = 1,
    LOGIN_BYRECONN = 2,
    PVP_PING = 1,
}

public class ILRuntime_msgid
{
    static ILRuntime_msgid()
    {

        //Initlize();

    }
    public static void Initlize()
    {


    }
}

#pragma warning restore CS1591, CS0612, CS3021
